#!/bin/sh

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Here you can add everything you want to perform before a commit is made
# For example:
#   * Linter checks
#   * Reagange code
#   * Reformat code
#   * Optimze imports

pylint
eslint
